---
version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - markdorison
    assignees:
      - markdorison
    labels:
      - "dependencies"
      - "php"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - markdorison
    assignees:
      - markdorison
